default_language_version:
  python: python3
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        files: .py$
  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
        files: .py$
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        files: .py$